---
- hosts: leaf03
  vars:
    description: “this is a leaf switch”
  remote_user: cumulus
  tasks:
  - name: write the quagga config file
    become: true
    template: src=leaf02quagga.txt dest=/etc/quagga/Quagga.conf
    notify:
    - restart quagga
  - name: ensure quagga is running
    become: true
    service: name=quagga state=started
  handlers:
    - name: restart quagga
      service: name=quagga state=restarted
