---

- name: Add spine conf
  hosts: spine01
  remote_user: cumulus

  tasks:

    - name: add conf
      nclu:
        commands:
            - add interface swp5
            - add interface swp5 ipv6 nd ra-interval 10
            - del interface swp5 ipv6 nd suppress-ra
            - add bgp neighbor swp5 interface peer-group fabric
